//CHAPTER # 03:
//VARIABLES FOR NUMBERS;
// QUESTION # 01;
// Declare a variable called age and assign your age to it
// let age = 17;  
// alert("My age is:" + age + " "  + "years old");
// QUESTION #02;
// Declare and initialize a variable to track the number of visit;
// let visitCount = 5;
// alert("You have visited this site" + " " + visitCount + " " + "times");
// QUESTION # O3;
// Declare a variable called birthYear and assign your birth year to it;
// var birthYear = 2008;
// document.write("My birth year is" + " " + birthYear + ".<br>");
// document.write("<b>"+"Data type of my declared variable is " + typeof birthYear + "." + "</b>");
// QUESTION # 04;
// Store visitor's information in variable;
// var visitorName = "Ali";
// var productTitle = "T-shirt";
// var quantity = 5;
// document.write("<h3>" + visitorName + " " +  "ordered" + " " +  quantity + " " + productTitle + " " + "from" + " " +  "(s) on www.xyzClothing.com</h3>");
//FINISHED//
//CHAPTER # 04;
//QUESTION # 01;
// Declare 3 variables in one statement;
// let userName = "Ali"; userAge = 16; city = "Karachi";
// console.log(userName);
// console.log(userAge);
// console.log(city);
//QUESTION # 02;
// Legal Variables;
// var myName = "Ayesha";
// var age_21 = 21;
// var $price = 100;
// var _location = "Karachi";
// var totalScore = 50;
// console.log(myName);
// console.log(age_21);
// console.log($price);
// console.log(_location);
// console.log(totalScore);
//Illegal Variables;
// let let = "One";
// let @age = 25;
// let user name = "Sara";
// let user-name = "Nimra";
// let 2user = "Ahmed";
//QUESTION # 03;
 // Display heading in the browser;
//  document.write("<h1>Rules for naming JS Variables</h1>");
//  document.write("Variables names can only contain letters, numbers, underscores (_) or dollar signs ($).For example: <b>$name</b>, <b>_name</b>, or <b>name</b></br>");
// document.write("Variables names are case <b>sensitive</b>.</br>");
// document.write("Variable names should not be JS <b><i>keywords</b></i></br>");
//End--
//CHAPTER # 05;
// //QUESTION # 01;
// let number1 = 3;
// let number2 = 5;
// let sum = number1 + number2;
// document.write("The sum of" + " " +  number1 + "and" + " " + number2 + " " + "is" + " " + sum );
// //QUESTION # 02;
// let number3 = 7;
// let number4 = 3;
// let subtraction = number3 - number4;
// let multiplication = number3 * number4;
// let division = number3 / number4;
// let modulus = number3 % number4;
// document.write("<h1>Math Operations</h1>");
// document.write("<p>The subtraction of " + number3 + " and " + number4 + " is: " + subtraction + "</p>");
// document.write("<p>The multiplication of " + number3 + " and " + number4 + " is: " + multiplication + "</p>");
// document.write("<p>The division of " + number3 + " and " + number4 + " is: " + division + "</p>");
// document.write("<p>The modulus of " + number3 + " and " + number4 + " is: " + modulus + "</p>");
// QUESTION # O3;
// Part a: declare variable;
//  let number;
// Part b:showing value; 
// document.write("value after variable declaration is:" + number + "<br>");
// Part c:initialization; 
// var someNum = 5;
// part d:showing in browser;
// document.write("initialized value is:" + someNum  +"<br>");
// Part e: increment;
// someNum++;
// // part f: showing;
// document.write("value after increment is:" + someNum + "<br>");
// part g: increment 7;
// someNum += 7;
// part h: showing;
// document.write("value after adding 7 is:" + someNum + "<br>");
// part i:Decrement;
// someNum--;
// part j:showing;
// document.write("value after decrement is:" + someNum + "<br>");
// part k:Remainder;
// var remain = someNum % 3;
// part l:showing;
// document.write("The remainder is:" + remain + "<br>");
// //QUESTION 4:TICKET PRICE CALCULATION;
// let ticketPrice = 600;
// let numberOfTickets = 5;
// let totalCost = ticketPrice * numberOfTickets;

// document.write("Total cost to buy " + numberOfTickets + " tickets to a movie is " + totalCost + " PKR");
// QUESTION 5:display multiplication table;
// let multiple = 4;
// document.write("<h2> Multiplication table of" + " " + multiple + "</h2>");
// document.write(multiple + " " + "x 1 =" + " " + (multiple*1) + "<br>");
// document.write(multiple + " " + "x 2 =" + " " + (multiple*2) + "<br>");
// document.write(multiple + " " + "x 3 =" + " " + (multiple*3) + "<br>");
// document.write(multiple + " " + "x 4 =" + " " + (multiple*4) + "<br>");
// document.write(multiple + " " + "x 5 =" + " " + (multiple*5) + "<br>");
// document.write(multiple + " " + "x 6 =" + " " + (multiple*6) + "<br>");
// document.write(multiple + " " + "x 7 =" + " " + (multiple*7) + "<br>");
// document.write(multiple + " " + "x 8 =" + " " + (multiple*8) + "<br>");
// document.write(multiple + " " + "x 9 =" + " " + (multiple*9) + "<br>");
// document.write(multiple + " " + "x 10 =" + " " + (multiple*10) + "<br>");
// QUESTION 6:temperature converter;
// let celsius = 25;
// document.write("<h2> TEMPERATURE CONVERTER<h2>");
// celsius to fahrenhiet;
// let fahrenhietResult = (25 * 9/5) + 32;
// document.write(celsius + "°C is" + fahrenhietResult + "°F<br>");
// fahrenhiet to celcius;
// let fahrenhiet = 70;
// let celciusResult = (70 - 32)* 5/9;
// document.write(fahrenhiet + "°F is" + celciusResult + "°C<br>");
// QUESTION 7:SHOPPING CART;
// var priceItem1 = 650;
// var priceItem2 = 100;
// var quantityItem1 = 3;
// var quantityItem2 = 7;
// var shippingCharges = 100;
// let finalCost = (priceItem1 * quantityItem1) + (priceItem2 * quantityItem2) + shippingCharges;
// document.write("<h1>SHOPPING CART</h1>");
// document.write("Price of item 1 is " + priceItem1 + "<br>");
// document.write("Quantity of item 1 is " + quantityItem1 + "<br>");
// document.write("Price of item 2 is " + priceItem2 + "<br>");
// document.write("Quantity of item 2 is " + quantityItem2 + "<br>");
// document.write("Shipping Charges is " + shippingCharges + "<br>");
// document.write("total cost of your order is " + finalCost);
// QUESTION 8: STUDENT PERCENTAGE CALCULATOR;
// let totalMarks = 980;
// let marksObtained = 804;
// let percentage = (marksObtained / totalMarks) * 100;
// document.write("<h2>MARKS SHEET</h2>");
// document.write("Total Marks: " + totalMarks + "<br>");
// document.write("Marks obtained: " + marksObtained + "<br>");
// document.write("Percentage: " + percentage + "%<br>");
// QUESTION 09:CONVERT FORIEGN CURRENCY INTO PKR;
// let usdToPKR = 104.80;
// let riyalToPkR = 28;
// let totalPKR = (10 * usdToPKR) + (25 * riyalToPkR);
// document.write("<h2>CURRENCY IN PKR</h2>");
// document.write("Total currency in PKR: " + totalPKR);
// QUESTION 10:ARITHMATIC IN A SINGAL EXPRESSION;
// let num = 10;
// let express = ((10 + 5) * 10) / 2;
// document.write("<h2>ARITHMATIC IN A SINGAL EXPRESSION</h2>");
// document.write(express) + "<br>";
// // QUESTION 11: AGE CALCULATOR:
// var currentYear = 2025;
// var birthYear = 2008;
// var age1 = currentYear - birthYear;
// var age2 = age1 - 1;
// document.write("<h2>Age Calculator</h2>")
// document.write("They are either " + age1 + "or " + age2 + " years old " + "<br>");
// QUESTION 12: THE GEOMETRIZER;
// let radius = 20;
// let pi = 3.142;
// given = cicumference formula is 2 * radius * pi;
// let cicumference = 2 * radius * pi;
// document.write("<h2>THE GEOMETRIZER</h2>");
// document.write("The radius of a circle is: " + radius + "<br>");
// document.write("The cicumference of a circle is: " + cicumference + "<br>");
// given formula for area is = pi * radius * radius;
// let area = pi * radius * radius;
// document.write("The area of a circle is: " + area + "<br>");
// QUESTION 13: THE LIFE TIME SUPPLY CALCULATOR;
// let favSnack = "Dora Cakes";
// let currentAge = 17;
// let maxAge = 70;
// let perDay = "4 per day";
// let totalSnack = (maxAge - currentAge) * 365 * perDay;
// document.write("<h2>The lifetime supply calculator</h2>");
// document.write("Favourite Snack: " + favSnack + "<br>");
// document.write("Current age: " + currentAge + "<br>");
// document.write("Estimated maximum age: " + maxAge + "<br>");
// document.write("Amount of snacks per day: " + perDay + "<br>");
// document.write("You will need " + totalSnack + perDay + "to last you until the ripe of old age of " + maxAge);


